### ISSUE TITLE
No aprendiste bien el uso de jitjub

### ISSUE THREAD

**Issue by OrellanaMatias** [mrtorres7/learning-jitjub#2]
mal ahi kpo @mrtorres7

**Comment by OrellanaMatias** [comment]
![Uploading makeitmeme_5ykWl.jpeg…]()

**Comment by OrellanaMatias** [comment]
![stonks](https://github.com/mrtorres7/learning-jitjub/assets/144801268/7052357e-8e23-4775-b48e-41b935da178b)

**Comment by mrencu** [comment]
callate tio, soy muy pro en jitjub

**Comment by OrellanaMatias** [comment]
> callate tio, soy muy pro en jitjub

bien ahi crack, cerra el issue y te dan una insignia
